<?php
return array(
'id'=>'1',
'SHOP_TITLE'=>'动力矿机 - 区块链硬件解决方案专家a',
'SHOP_NAME'=>'车技源',
'SHOP_KEYWORD'=>'矿机,比特矿机,比特矿机图片,显卡挖矿,矿机托管,显卡矿机,ETH矿机,ZEC矿机,区块链投资,挖矿,矿工,区块链,比特币,以太币,以太坊,门罗币,ETH,BTC,ZEC,XMR,XMC',
'SHOP_DESCRIPTION'=>'动力矿机是一家全球领先的加密货币硬件设备专业制造商，团队集合了众多行业内专业人士，在半年内研发出适用于多种虚拟货币的显卡矿机，同时提供比特矿机客户服务及售后支持。',
'SHOP_SEARCH_KEYWORD'=>'矿机,比特矿机,比特矿机图片,显卡挖矿,矿机托管,显卡矿机,ETH矿机,ZEC矿机,区块链投资,挖矿,矿工,区块链,比特币,以太币,以太坊,门罗币,ETH,BTC,ZEC,XMR,XMC',
'SHOP_TEL'=>'0755-88888888',
'ONLINE_QQ'=>'',
'ONLINE_TIME'=>'周一至周六 9:00-18:00',
'ICP_LICENSE'=>'粤ICP备18037387号-1',
'COMPANY'=>'',
'EMAIL'=>'',
'TEMPLATE'=>'red',
'SHOP_LANG'=>'',
'COMPANY_ADDRESS'=>'',
'LOGOIMG'=>'',
'SHOP_URL'=>'https://wx.cjycar.com/wxapi/accbind',
'SHOP_OPEN'=>'1',
'PRICE_RATE'=>'59700.000',
'MAIL_ON'=>'1',
'SMS_ON'=>'1',
'APPID'=>'wx4291621f5c04d7fd',
'AppSecret'=>'wx4291621f5c04d7fd2sdfsdfsdfsfsd',
'MCHID'=>'',
'MCHKey'=>'',
'expires_in'=>'1612118443',
'access_token'=>'',
'shareInt'=>'1',
'mapkey'=>'E68wcHQLvNIIeGGamUBCyxnjrjeya63c',
'shareday'=>'180',
'wxlogInt'=>'1',
'language_id'=>'0',
'is_test'=>'0',
'is_review'=>'0',
);
 ?>